version: "3.9"
services:
  frontend:
    image: ghcr.io/kruchy/zresztek-frontend:latest
    container_name: zresztek-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_PATH: ${REACT_APP_API_PATH}
    ports:
      - "80:80"
    networks:
      - nginx-proxy

  backend:
    image: ghcr.io/kruchy/zresztek-backend:latest
    container_name: zresztek-backend
    restart: unless-stopped
    environment:
      PORT: "${API_PORT}"
      NODE_ENV: "production"
    ports:
      - "4000:${API_PORT}"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
