version: "3.9"
services:
  frontend:
    image: ghcr.io/kruchy/zresztek-frontend:latest
    container_name: zresztek-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      args:
        REACT_APP_API_PATH: "${API_PATH}"
    ports:
      - "80:80"
    networks:
      - nginx-proxy

  backend:
    image: ghcr.io/kruchy/zresztek-backend:latest
    container_name: zresztek-backend
    restart: unless-stopped
    build:
      context: ./backend
      args:
        PORT: "${API_PORT}"
    environment:
      PORT: "${API_PORT}"
      CONSTANT_INGREDIENTS: "${CONSTANT_INGREDIENTS}"
      SINGLE_VARYING_INGREDIENTS: "${SINGLE_VARYING_INGREDIENTS}"
      SINGLE_RECIPE_PROMPT: "${SINGLE_RECIPE_PROMPT}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      GIT_LAST_COMMIT_SHA: "${GIT_LAST_COMMIT_SHA}"
      DEPLOY_TIME: "${DEPLOY_TIME}"
      NODE_ENV: "production"
    ports:
      - "4000:${API_PORT}"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
