const knownIngredients = [
  "amaretto",
  "ananas",
  "awokado",
  "bakłażan",
  "banan",
  "bazylia",
  "boczek",
  "brokuł",
  "brzoskwinia",
  "cebula",
  "chili",
  "chleb",
  "ciasto francuskie",
  "cukier",
  "cukier puder",
  "cukier trzcinowy",
  "cukier wanilinowy",
  "cukinia",
  "cynamon",
  "cytryna",
  "czerwona fasola",
  "czerwona kapusta",
  "czerwona soczewica",
  "czosnek",
  "daktyle",
  "dynia",
  "figa",
  "filet z dorsza",
  "filet z kurczaka",
  "gałka muszkatołowa",
  "goździk",
  "grapefruit",
  "gruszka",
  "imbir",
  "jabłko",
  "jajko",
  "jogurt",
  "kakao",
  "kalafior",
  "kapusta",
  "kardamon",
  "karkówka",
  "kasza gryczana",
  "kasza jaglana",
  "ketchup",
  "kiwi",
  "kminek",
  "kokos",
  "kolendra",
  "koper włoski",
  "koperek",
  "krewetki",
  "kukurydza",
  "kurkuma",
  "kuskus",
  "limonka",
  "łosoś",
  "majonez",
  "mąka",
  "makaron",
  "malina",
  "mandarynka",
  "mango",
  "marchew",
  "masło",
  "mięso mielone",
  "miód",
  "mleko",
  "musztarda",
  "ocet",
  "ogórek",
  "olej",
  "oregano",
  "orzechy laskowe",
  "orzechy nerkowca",
  "orzechy włoskie",
  "papryka",
  "pieprz",
  "pietruszka",
  "pistacje",
  "płatki owsiane",
  "pomarańcza",
  "pomidor",
  "por",
  "proszek do pieczenia",
  "rozmaryn",
  "rukola",
  "rum",
  "ryż",
  "sałata",
  "śledź",
  "śliwka",
  "śliwka suszona",
  "śliwka węgierka",
  "śmietana",
  "sól",
  "sos czosnkowy",
  "sos pomidorowy",
  "sos sojowy",
  "stek wołowy",
  "suszone morele",
  "szalotka",
  "szczypiorek",
  "szparagi",
  "szpinak",
  "szynka",
  "truskawka",
  "twaróg",
  "tymianek",
  "wanilia",
  "winogrona",
  "woda",
  "zielona soczewica",
  "ziemniak",
  "żurawina",
];

module.exports = knownIngredients;
