const knownIngredients = [
"adzuki (roślina strączkowa)",
"amaretto",
"ananas",
"arbuzy",
"awokado",
"bakłażan",
"banan",
"batat",
"bazylia",
"biała czekolada",
"biała fasola",
"białko jajka",
"bita śmietana",
"bób",
"boczek",
"borówki",
"bourbon",
"brązowy ryż",
"brokuł",
"brzoskwinia",
"bulion",
"buraki",
"buraki gotowane",
"cebula",
"chili",
"chleb",
"chleb tostowy",
"chrzan",
"ciasto francuskie",
"ciecierzyca",
"cukier",
"cukier kokosowy",
"cukier puder",
"cukier trzcinowy",
"cukier wanilinowy",
"cukinia",
"cynamon",
"cytryna",
"czerwona cebula",
"czerwona fasola",
"czerwona kapusta",
"czerwona soczewica",
"czosnek",
"daktyle",
"dynia",
"edamame (młoda soja)",
"feta (ser)",
"figa",
"filet z dorsza",
"filet z kurczaka",
"fistaszki",
"gałka muszkatołowa",
"gorgonzola (ser)",
"goździk",
"grapefruit",
"groszek",
"gruszka",
"grzyby marynowane",
"halloumi (ser)",
"homar",
"imbir",
"indyk",
"jabłko",
"jajko",
"jarmuż",
"jogurt",
"kabaczek",
"kabanosy",
"kakao",
"kalafior",
"kalarepa",
"kamut (rodzaj pszenicy)",
"kapusta",
"kardamon",
"karkówka",
"kasza gryczana",
"kasza jaglana",
"kefir",
"ketchup",
"kiełbasa",
"kiwi",
"kminek",
"kminek rzymski",
"kokos",
"kolendra",
"komosa ryżowa (quinoa)",
"koper włoski",
"koperek",
"krewetki",
"kukurydza",
"kurczak",
"kurkuma",
"kuskus",
"kwas chlebowy",
"laska wanilii",
"limonka",
"łosoś",
"majonez",
"mąka",
"makaron",
"malina",
"mandarynka",
"mango",
"marchew",
"mascarpone",
"masło",
"masło klarowane",
"masło orzechowe",
"melon",
"mięso mielone",
"mięso wieprzowe",
"mięso wołowe",
"mięta",
"migdały",
"miód",
"mleko",
"młoda kapusta",
"mortadella (szynka włoska)",
"mozzarella (ser)",
"musztarda",
"musztarda Dijon",
"napój kokosowy",
"napój migdałowy",
"napój owsiany",
"natka pietruszki",
"nduja",
"ocet",
"ogórek",
"ogórki kiszone",
"olej",
"olej lniany",
"olej sezamowy",
"oliwa z oliwek",
"oliwki",
"oregano",
"oregano (dodatek do potraw)",
"orzechy laskowe",
"orzechy nerkowca",
"orzechy włoskie",
"owoce goji",
"papryka",
"parmezan (ser)",
"parówki",
"pęczak",
"pieczarki",
"pieprz",
"pietruszka",
"pistacje",
"płatki owsiane",
"polędwica wieprzowa",
"pomarańcza",
"pomidor",
"por",
"proszek do pieczenia",
"quorn (białko roślinne)",
"rabarbar",
"ricotta (ser)",
"rozmaryn",
"rukola",
"rum",
"ryż",
"ryż basmati",
"ryż jaśminowy",
"sałata",
"seler",
"seler naciowy",
"ser brie",
"ser camembert",
"ser pleśniowy",
"ser żółty",
"serek śmietankowy",
"sezam",
"śledź",
"śliwka",
"śliwka suszona",
"śliwka węgierka",
"smalec",
"śmietana",
"śmietana 12%",
"śmietana 18%",
"śmietana 30%",
"śmietana 36%",
"soja",
"sok pomarańczowy",
"sól",
"sos czosnkowy",
"sos pomidorowy",
"sos sojowy",
"stek wołowy",
"suche bułki",
"suszone morele",
"syrop klonowy",
"szalotka",
"szałwia",
"szczypiorek",
"szparagi",
"szpinak",
"szynka",
"szynka parmeńska",
"tofu (ser sojowy)",
"trawa pszeniczna",
"truskawka",
"twaróg",
"tymianek",
"wanilia",
"wino czerwone",
"winogrona",
"włoszczyzna",
"wołowina",
"zielona soczewica",
"ziemniak",
"żółta fasola",
"żółtko jajka",
"żurawina",
"żurawina suszona"]

module.exports = knownIngredients;

