const spices = [
    "bazylia",
    "chili",
    "chrzan",
    "cynamon",
    "gałka muszkatołowa",
    "goździk",
    "imbir",
    "kardamon",
    "kminek",
    "kminek rzymski",
    "kolendra",
    "koper włoski",
    "koperek",
    "kurkuma",
    "mięta",
    "oregano",
    "pieprz",
    "rozmaryn",
    "szałwia",
    "szczypiorek",
    "tymianek",
    "wanilia",
    "seler naciowy",
    "natka pietruszki",
    "sezam",
    "pieprz",
    "sól"]

module.exports = spices;
