const knownIngredients = [
  "adzuki (roślina strączkowa)",
  "amaretto",
  "ananas",
  "arbuzy",
  "awokado",
  "bakłażan",
  "banan",
  "bazylia",
  "biała czekolada",
  "biała fasola",
  "bób",
  "boczek",
  "borówki",
  "bourbon",
  "brązowy ryż",
  "brokuł",
  "brzoskwinia",
  "cebula",
  "chili",
  "chleb",
  "ciasto francuskie",
  "ciecierzyca",
  "cukier",
  "cukier kokosowy",
  "cukier puder",
  "cukier trzcinowy",
  "cukier wanilinowy",
  "cukinia",
  "cynamon",
  "cytryna",
  "czerwona fasola",
  "czerwona kapusta",
  "czerwona soczewica",
  "czosnek",
  "daktyle",
  "dynia",
  "edamame (młoda soja)",
  "feta (ser)",
  "figa",
  "filet z dorsza",
  "filet z kurczaka",
  "fistaszki",
  "gałka muszkatołowa",
  "gorgonzola (ser)",
  "goździk",
  "grapefruit",
  "groszek",
  "gruszka",
  "halloumi (ser)",
  "homar",
  "imbir",
  "indyk",
  "jabłko",
  "jajko",
  "jarmuż",
  "jogurt",
  "kabaczek",
  "kakao",
  "kalafior",
  "kalarepa",
  "kamut (rodzaj pszenicy)",
  "kapusta",
  "kardamon",
  "karkówka",
  "kasza gryczana",
  "kasza jaglana",
  "kefir",
  "ketchup",
  "kiwi",
  "kminek",
  "kminek rzymski",
  "kokos",
  "kolendra",
  "komosa ryżowa (quinoa)",
  "koper włoski",
  "koperek",
  "krewetki",
  "kukurydza",
  "kurczak",
  "kurkuma",
  "kuskus",
  "kwas chlebowy",
  "limonka",
  "łosoś",
  "majonez",
  "mąka",
  "makaron",
  "malina",
  "mandarynka",
  "mango",
  "marchew",
  "mascarpone",
  "masło",
  "masło orzechowe",
  "melon",
  "mięso mielone",
  "mięso wieprzowe",
  "mięso wołowe",
  "migdały",
  "miód",
  "mleko",
  "młoda kapusta",
  "mozzarella (ser)",
  "musztarda",
  "musztarda Dijon",
  "natka pietruszki",
  "ocet",
  "ogórek",
  "olej",
  "olej lniany",
  "olej sezamowy",
  "oliwki",
  "oregano",
  "oregano (dodatek do potraw)",
  "orzechy laskowe",
  "orzechy nerkowca",
  "orzechy włoskie",
  "owoce goji",
  "papryka",
  "parmezan (ser)",
  "pęczak",
  "pieczarki",
  "pieprz",
  "pietruszka",
  "pistacje",
  "płatki owsiane",
  "polędwica wieprzowa",
  "pomarańcza",
  "pomidor",
  "por",
  "proszek do pieczenia",
  "quorn (białko roślinne)",
  "rabarbar",
  "ricotta (ser)",
  "rozmaryn",
  "rukola",
  "rum",
  "ryż",
  "ryż basmati",
  "ryż jaśminowy",
  "sałata",
  "ser brie",
  "ser camembert",
  "ser pleśniowy",
  "ser żółty",
  "serek śmietankowy",
  "sezam",
  "śledź",
  "śliwka",
  "śliwka suszona",
  "śliwka węgierka",
  "śmietana",
  "soja",
  "sól",
  "sos czosnkowy",
  "sos pomidorowy",
  "sos sojowy",
  "stek wołowy",
  "suszone morele",
  "szalotka",
  "szałwia",
  "szczypiorek",
  "szparagi",
  "szpinak",
  "szynka",
  "szynka parmeńska",
  "tofu (ser sojowy)",
  "trawa pszeniczna",
  "truskawka",
  "twaróg",
  "tymianek",
  "wanilia",
  "winogrona",
  "włoszczyzna",
  "woda",
  "wołowina",
  "zielona soczewica",
  "ziemniak",
  "żółta fasola",
  "żółtko jajka",
  "żurawina",
  "żurawina suszona"]

module.exports = knownIngredients;
