const knownIngredients = [
  "adzuki (roślina strączkowa)",
  "amaretto",
  "ananas",
  "arbuzy",
  "awokado",
  "bakłażan",
  "banan",
  "batat",
  "biała czekolada",
  "biała fasola",
  "białko jajka",
  "bita śmietana",
  "bób",
  "boczek",
  "borówki",
  "bourbon",
  "brązowy ryż",
  "brokuł",
  "brzoskwinia",
  "bulion",
  "buraki",
  "buraki gotowane",
  "cebula",
  "chleb",
  "chleb tostowy",
  "ciasto francuskie",
  "ciecierzyca",
  "cukier",
  "cukier kokosowy",
  "cukier puder",
  "cukier trzcinowy",
  "cukier wanilinowy",
  "cukinia",
  "cytryna",
  "czerwona cebula",
  "czerwona fasola",
  "czerwona kapusta",
  "czerwona soczewica",
  "czosnek",
  "daktyle",
  "dynia",
  "edamame (młoda soja)",
  "feta (ser)",
  "figa",
  "filet z dorsza",
  "filet z kurczaka",
  "fistaszki",
  "gorgonzola (ser)",
  "grapefruit",
  "groch",
  "groszek",
  "gruszka",
  "grzyby marynowane",
  "halloumi (ser)",
  "homar",
  "indyk",
  "jabłko",
  "jajko",
  "jarmuż",
  "jogurt",
  "kabaczek",
  "kabanosy",
  "kakao",
  "kalafior",
  "kalarepa",
  "kamut (rodzaj pszenicy)",
  "kapusta",
  "karkówka",
  "kasza gryczana",
  "kasza jaglana",
  "kefir",
  "ketchup",
  "kiełbasa",
  "kiwi",
  "kokos",
  "komosa ryżowa (quinoa)",
  "krewetki",
  "kukurydza",
  "kurczak",
  "kuskus",
  "kwas chlebowy",
  "laska wanilii",
  "limonka",
  "łosoś",
  "majonez",
  "mąka",
  "makaron",
  "malina",
  "mandarynka",
  "mango",
  "marchew",
  "mascarpone",
  "masło",
  "masło klarowane",
  "masło orzechowe",
  "melon",
  "mięso mielone",
  "mięso wieprzowe",
  "mięso wołowe",
  "migdały",
  "miód",
  "mleko",
  "młoda kapusta",
  "mortadella (szynka włoska)",
  "mozzarella (ser)",
  "musztarda",
  "musztarda Dijon",
  "napój kokosowy",
  "napój migdałowy",
  "napój owsiany",
  "nduja",
  "ocet",
  "ogórek",
  "ogórki kiszone",
  "olej",
  "olej lniany",
  "olej sezamowy",
  "oliwa z oliwek",
  "oliwki",
  "oregano (dodatek do potraw)",
  "orzechy laskowe",
  "orzechy nerkowca",
  "orzechy włoskie",
  "owoce goji",
  "papryka",
  "parmezan (ser)",
  "parówki",
  "pęczak",
  "pieczarki",
  "pietruszka",
  "pistacje",
  "płatki owsiane",
  "polędwica wieprzowa",
  "pomarańcza",
  "pomidor",
  "por",
  "proszek do pieczenia",
  "quorn (białko roślinne)",
  "rabarbar",
  "ricotta (ser)",
  "rukola",
  "rum",
  "ryż",
  "ryż basmati",
  "ryż jaśminowy",
  "sałata",
  "seler",
  "ser brie",
  "ser camembert",
  "ser pleśniowy",
  "ser żółty",
  "serek śmietankowy",
  "śledź",
  "śliwka",
  "śliwka suszona",
  "śliwka węgierka",
  "smalec",
  "śmietana",
  "śmietana 12%",
  "śmietana 18%",
  "śmietana 30%",
  "śmietana 36%",
  "soja",
  "sok pomarańczowy",
  "sos czosnkowy",
  "sos pomidorowy",
  "sos sojowy",
  "stek wołowy",
  "suche bułki",
  "suszone morele",
  "syrop klonowy",
  "szalotka",
  "szparagi",
  "szpinak",
  "szynka",
  "szynka parmeńska",
  "tofu (ser sojowy)",
  "trawa pszeniczna",
  "truskawka",
  "twaróg",
  "wino czerwone",
  "winogrona",
  "włoszczyzna",
  "wołowina",
  "zielona soczewica",
  "ziemniak",
  "żółta fasola",
  "żółtko jajka",
  "żurawina",
  "żurawina suszona"]

module.exports = knownIngredients;

