name: Build, Test and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      if: contains(github.event.head_commit.modified, matrix.app)
      run: |
        cd ${{ matrix.app }}
        npm ci

    - name: Run tests
      if: contains(github.event.head_commit.modified, matrix.app)
      run: |
        cd ${{ matrix.app }}
        npm test

  build_and_push_docker_images:
    needs: build_and_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      if: contains(github.event.head_commit.modified, matrix.app)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      if: contains(github.event.head_commit.modified, matrix.app)
      run: |
        cd ${{ matrix.app }}
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.app }}:${{ github.sha }}
